### ISSUE TITLE
断点重新训练报错

### ISSUE THREAD

**Issue by scutfrank** [yangxh11/P2P-Net#3]
Traceback (most recent call last):
  File "D:/1.Study/PycharmProjects/Reproduce/P2P-Net-main/train.py", line 166, in <module>
    train()
  File "D:/1.Study/PycharmProjects/Reproduce/P2P-Net-main/train.py", line 66, in train
    net = net.to(device)
AttributeError: 'collections.OrderedDict' object has no attribute 'to'
![image](https://user-images.githubusercontent.com/24981824/201254054-1b00b2bb-7828-453d-a65b-0c0b909a451a.png)

**Comment by yangxh11** [comment]
Thanks. I currently can not access the code/data/device right now.
The reason might be that we only save the state_dict of the model, so if you want to resume, please try the following steps:
```python
if args.resume != "":
  # init model
  net = load_model(backbone=args.backbone, pretrain=True, require_grad=True, classes_num=classes_num, topn=topn)
  # load weights
  net.load_state_dict(torch.load(args.resume))
```
Feel free to contact me anytime.
